"""create initial models

Revision ID: a6b308e0ea40
Revises: 
Create Date: 2026-04-16 23:50:46.467942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b308e0ea40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('primary_phone', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_slug')
    )
    op.create_index('idx_client_primary_email', 'client', ['primary_email'], unique=False)
    op.create_index('idx_client_status', 'client', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), server_default=sa.text("'email'"), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('mailbox', sa.String(), server_default=sa.text("'INBOX'"), nullable=False),
    sa.Column('imap_uid', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('thread_key', sa.String(), nullable=True),
    sa.Column('in_reply_to', sa.String(), nullable=True),
    sa.Column('references_header', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('received_on', sa.DateTime(), nullable=False),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('imap_internal_date', sa.DateTime(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('flags_json', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attachment_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('body_text_raw', sa.Text(), nullable=True),
    sa.Column('body_html_raw', sa.Text(), nullable=True),
    sa.Column('body_text_clean', sa.Text(), nullable=True),
    sa.Column('body_hash', sa.String(), nullable=True),
    sa.Column('clean_body_hash', sa.String(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_messages_account_mailbox_uid', 'messages', ['account_id', 'mailbox', 'imap_uid'], unique=True)
    op.create_index('idx_messages_from_email', 'messages', ['from_email'], unique=False)
    op.create_index('idx_messages_message_id', 'messages', ['message_id'], unique=True)
    op.create_index('idx_messages_status_received_on', 'messages', ['status', 'received_on'], unique=False)
    op.create_index('idx_messages_thread_key', 'messages', ['thread_key'], unique=False)
    op.create_table('ai_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), server_default=sa.text("'extract_tasks'"), nullable=False),
    sa.Column('message_row_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('http_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_row_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_log_message_row_id', 'ai_log', ['message_row_id'], unique=False)
    op.create_index('idx_ai_log_provider_model', 'ai_log', ['provider', 'model'], unique=False)
    op.create_index('idx_ai_log_status', 'ai_log', ['status'], unique=False)
    op.create_table('message_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_row_id', sa.Integer(), nullable=False),
    sa.Column('address_role', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_row_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_addresses_email_address', 'message_addresses', ['email_address'], unique=False)
    op.create_index('idx_message_addresses_message_row_id', 'message_addresses', ['message_row_id'], unique=False)
    op.create_index('idx_message_addresses_role', 'message_addresses', ['address_role'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_row_id', sa.Integer(), nullable=False),
    sa.Column('part_index', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filename_normalized', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('is_inline', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('extraction_status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_row_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_attachments_content_hash', 'message_attachments', ['content_hash'], unique=False)
    op.create_index('idx_message_attachments_extraction_status', 'message_attachments', ['extraction_status'], unique=False)
    op.create_index('idx_message_attachments_message_row_id', 'message_attachments', ['message_row_id'], unique=False)
    op.create_table('message_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_row_id', sa.Integer(), nullable=False),
    sa.Column('filter_name', sa.String(), nullable=False),
    sa.Column('filter_value', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_row_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_filters_filter_name', 'message_filters', ['filter_name'], unique=False)
    op.create_index('idx_message_filters_message_filter', 'message_filters', ['message_row_id', 'filter_name'], unique=True)
    op.create_index('idx_message_filters_message_row_id', 'message_filters', ['message_row_id'], unique=False)
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_row_id', sa.Integer(), nullable=False),
    sa.Column('raw_rfc822', sa.LargeBinary(), nullable=False),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_row_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_row_id')
    )
    op.create_index('idx_raw_messages_message_row_id', 'raw_messages', ['message_row_id'], unique=True)
    op.create_table('task_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('requested_on', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_slug')
    )
    op.create_index('idx_task_groups_client_id', 'task_groups', ['client_id'], unique=False)
    op.create_index('idx_task_groups_priority', 'task_groups', ['priority'], unique=False)
    op.create_index('idx_task_groups_source_message_id', 'task_groups', ['source_message_id'], unique=False)
    op.create_index('idx_task_groups_status', 'task_groups', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('requested_on', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('task_group_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('ai_log_id', sa.Integer(), nullable=True),
    sa.Column('extracted_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_log_id'], ['ai_log.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_group_id'], ['task_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_ai_log_id', 'tasks', ['ai_log_id'], unique=False)
    op.create_index('idx_tasks_expected_delivery_date', 'tasks', ['expected_delivery_date'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_source_message_id', 'tasks', ['source_message_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_task_group_id', 'tasks', ['task_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_task_group_id', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_source_message_id', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_expected_delivery_date', table_name='tasks')
    op.drop_index('idx_tasks_ai_log_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_task_groups_status', table_name='task_groups')
    op.drop_index('idx_task_groups_source_message_id', table_name='task_groups')
    op.drop_index('idx_task_groups_priority', table_name='task_groups')
    op.drop_index('idx_task_groups_client_id', table_name='task_groups')
    op.drop_table('task_groups')
    op.drop_index('idx_raw_messages_message_row_id', table_name='raw_messages')
    op.drop_table('raw_messages')
    op.drop_index('idx_message_filters_message_row_id', table_name='message_filters')
    op.drop_index('idx_message_filters_message_filter', table_name='message_filters')
    op.drop_index('idx_message_filters_filter_name', table_name='message_filters')
    op.drop_table('message_filters')
    op.drop_index('idx_message_attachments_message_row_id', table_name='message_attachments')
    op.drop_index('idx_message_attachments_extraction_status', table_name='message_attachments')
    op.drop_index('idx_message_attachments_content_hash', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('idx_message_addresses_role', table_name='message_addresses')
    op.drop_index('idx_message_addresses_message_row_id', table_name='message_addresses')
    op.drop_index('idx_message_addresses_email_address', table_name='message_addresses')
    op.drop_table('message_addresses')
    op.drop_index('idx_ai_log_status', table_name='ai_log')
    op.drop_index('idx_ai_log_provider_model', table_name='ai_log')
    op.drop_index('idx_ai_log_message_row_id', table_name='ai_log')
    op.drop_table('ai_log')
    op.drop_index('idx_messages_thread_key', table_name='messages')
    op.drop_index('idx_messages_status_received_on', table_name='messages')
    op.drop_index('idx_messages_message_id', table_name='messages')
    op.drop_index('idx_messages_from_email', table_name='messages')
    op.drop_index('idx_messages_account_mailbox_uid', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_client_status', table_name='client')
    op.drop_index('idx_client_primary_email', table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
